import './globals.css';
import { Manrope } from 'next/font/google';

export const manrope = Manrope({
  subsets: ['latin', 'cyrillic'],
  variable: '--font-manrope',
});

export const metadata = {
  title: 'Next graph component',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body className={`${manrope.variable} font-manrope`}>{children}</body>
    </html>
  );
}
